import type { Wine } from "../../types/products";

export const apiMock: Wine = {
  page: 1,
  totalPages: 1,
  itemsPerPage: 4,
  totalItems: 4,
  items: [
    {
      id: 0,
      image: "img/img.png",
      name: "Vinho 1",
      price: 175,
      discount: 45,
      priceMember: 96,
      priceNonMember: 114,
      type: "Tinto",
      classification: "Seco",
      size: "750 ml",
      rating: 4,
      avaliations: 292,
      country: "Portugal",
      region: "Dão",
      flag: "img/img.png",
      sommelierComment: "Lorem ipsum",
    },
    {
      id: 1,
      image: "img/img.png",
      name: "Vinho bom",
      price: 175,
      discount: 45,
      priceMember: 40,
      priceNonMember: 114,
      type: "Tinto",
      classification: "Seco",
      size: "750 ml",
      rating: 4,
      avaliations: 292,
      country: "Portugal",
      region: "Dão",
      flag: "img/img.png",
      sommelierComment: "Lorem ipsum",
    },
    {
      id: 2,
      image: "img/img.png",
      name: "Vinho 3",
      price: 175,
      discount: 45,
      priceMember: 130,
      priceNonMember: 114,
      type: "Tinto",
      classification: "Seco",
      size: "750 ml",
      rating: 4,
      avaliations: 292,
      country: "Portugal",
      region: "Dão",
      flag: "img/img.png",
      sommelierComment: "Lorem ipsum",
    },
    {
      id: 3,
      image: "img/img.png",
      name: "Vinho 4",
      price: 175,
      discount: 45,
      priceMember: 122,
      priceNonMember: 114,
      type: "Tinto",
      classification: "Seco",
      size: "750 ml",
      rating: 4,
      avaliations: 292,
      country: "Portugal",
      region: "Dão",
      flag: "img/img.png",
      sommelierComment: "Lorem ipsum",
    },
  ],
};
